<?php
/**
 * Magmodules.eu - http://www.magmodules.eu
 *
 * NOTICE OF LICENSE
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@magmodules.eu so we can send you a copy immediately.
 *
 * @category      Magmodules
 * @package       Magmodules_Channable
 * @author        Magmodules <info@magmodules.eu>
 * @copyright     Copyright (c) 2018 (http://www.magmodules.eu)
 * @license       http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
    <script type="text/javascript">
        //<![CDATA[
        function testModule() {
            new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
                parameters: {isAjax: 1},
                method: 'get',
                onCreate: function () {
                    $('test_result').hide();
                },
                onSuccess: function (transport) {
                    if (transport.responseText) {
                        $('test_result').update(transport.responseText);
                    } else {
                        $('test_result').update('Unkown error, please check logs');
                    }
                    $('test_result').show();
                }
            });
        }

        //]]>
    </script>
<?php echo $this->getButtonHtml() ?>